name: Swift CI

on:
  push:
    branches:
      - main
      - "abs/**"
  pull_request:

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Run tests
        run: swift test
      - name: Build
        run: swift build
